controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    propeller_controller:
      type: velocity_controllers/JointGroupVelocityController

propeller_controller:
  ros__parameters:
    joints:
      - cylinder_thruster_joint
