controller_manager:
  ros__parameters:
    update_rate: 30

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    propeller_controller:
      type: velocity_controllers/JointGroupVelocityController

    rudder_controller:
      type: forward_command_controller/ForwardCommandController

propeller_controller:
  ros__parameters:
    joints:
      - cylinder_thruster_joint

rudder_controller:
  ros__parameters:
    joints: ["pitch_joint", "yaw_joint"]
    interface_name: "position"
