controller_manager:
  ros__parameters:
    # A rate of 1 is good for debugging with prints
    # update_rate: 1
    update_rate: 30
    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]

    wheel_separation: 0.45
    wheel_radius: 0.1

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true

    # A rate of 1 is good for debugging with prints
    # publish_rate: 1.0
    publish_rate: 30.0

    # NOTE: has velocity limits, specific to humble (not in jazzy)
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0

    # NOTE: has velocity limits, specific to humble (not in jazzy)
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

    # All of a sudden, I was getting warnings about messages being dropped
    # because of being too old. This is possibly because of system clocks
    # out of sync, and if that's the case, then it should perhaps be fixed
    # properly. But otherwise, one can override the default of 0.5.
    # Another fix is to use `-p rate:=20` when running teleop keyboard.
    cmd_vel_timeout: 0.5
