<?xml version="1.0"?>
<robot name="auv" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="1.0" />
    <xacro:property name="base_radius" value="0.057" />
    <xacro:property name="thruster_radius" value="0.045" />
    <xacro:property name="thruster_thickness" value="0.01" />
    <xacro:property name="thruster_offset" value="0.01" />

    <link name="base_link" />

    <joint name="base_to_cylinder" type="fixed">
        <parent link="base_link" />
        <child link="cylinder_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="cylinder_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}" />
            </geometry>
            <material name="color1">
                <color rgba="0.8 0.8 0.8 1" />
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_radius*2} ${base_radius*2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>


        <inertial>
            <!-- this will make it neutral. use collision as volume -->
            <!-- <mass value="12.996" /> -->
            <mass value="12" />
            <!-- <mass value="10.996" /> -->

            <inertia
                ixx="0.018"
                ixy="0.0"
                ixz="0.0"
                iyy="1.1"
                iyz="0.0"
                izz="1.1"
            />
            <origin xyz="0 0 -0.03" rpy="0 0 0" />
        </inertial>

    </link>

</robot>