<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="1.0" />
    <xacro:property name="base_radius" value="0.06" />

    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${base_radius}" rpy="0 0 0" />
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size="${2*base_radius} ${2*base_radius} ${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        </collision>
        <xacro:cylinder_inertia m="12.0" r="${base_radius}" l="${base_length}"
            o_xyz="0 0 0" o_rpy="0 ${pi/2} 0" />
    </link>

</robot>