<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="rudder_base_side" value="0.05" />
    <xacro:property name="rudder_base_thickness" value="0.005" />

    <xacro:property name="axis_length" value="0.05" />
    <xacro:property name="axis_radius" value="0.005" />

    <xacro:property name="yaw_limit_rad" value="0.785" />
    <xacro:property name="pitch_limit_rad" value="0.5" />

    <link name="rudder_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${rudder_base_thickness} ${rudder_base_side} ${rudder_base_side}" />
            </geometry>
            <material name="yellowish1">
                <color rgba="0 0.8 0.8 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${rudder_base_thickness} ${rudder_base_side} ${rudder_base_side}" />
            </geometry>
        </collision>
        <xacro:box_inertia
            m="0.001"
            x="${rudder_base_thickness}"
            y="${rudder_base_side}"
            z="${rudder_base_side}"
            o_xyz="0 0 0"
            o_rpy="0 0 0"
        />
    </link>


    <link name="rod_link">
        <visual>
            <origin xyz="${axis_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${axis_radius}" length="${axis_length}" />
            </geometry>
            <material name="somecolor2">
                <color rgba="0.5 0.2 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="${axis_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${axis_radius}" length="${axis_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia
            m="0.001"
            r="${axis_radius}"
            l="${axis_length}"
            o_xyz="${axis_length/2} 0 0"
            o_rpy="0 ${pi/2} 0"
        />
    </link>

    <joint name="yaw_joint" type="revolute">
        <parent link="rudder_base" />
        <child link="rod_intermediate_link" />
        <origin xyz="${rudder_base_thickness/2} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-${yaw_limit_rad}" upper="${yaw_limit_rad}" effort="100" velocity="100" />
    </joint>

    <link name="rod_intermediate_link"></link>

    <joint name="pitch_joint" type="revolute">
        <parent link="rod_intermediate_link" />
        <child link="rod_link" />
        <axis xyz="0 1 0" />
        <limit lower="-${pitch_limit_rad}" upper="${pitch_limit_rad}" effort="100" velocity="100" />
    </joint>

</robot>