<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="rudder_base_radius" value="0.005" />

    <xacro:property name="axis_length" value="0.02" />
    <xacro:property name="axis_radius" value="0.001" />

    <xacro:property name="yaw_limit_rad" value="0.785" />
    <xacro:property name="pitch_limit_rad" value="0.5" />

    <xacro:property name="thruster_radius" value="0.03" />
    <xacro:property name="thruster_thickness" value="0.002" />
    <xacro:property name="thruster_blade_width" value="0.01" />

    <link name="rudder_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${rudder_base_radius}" />
            </geometry>
            <material name="yellowish1">
                <color rgba="0 0.8 0.8 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${rudder_base_radius}" />
            </geometry>
        </collision>
        <xacro:sphere_inertia
            m="0.001"
            r="${rudder_base_radius}"
            o_xyz="0 0 0"
            o_rpy="0 0 0"
        />
    </link>


    <link name="rod_link">
        <visual>
            <origin xyz="${axis_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${axis_radius}" length="${axis_length}" />
            </geometry>
            <material name="somecolor2">
                <color rgba="0.5 0.2 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="${axis_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${axis_radius}" length="${axis_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia
            m="0.001"
            r="${axis_radius}"
            l="${axis_length}"
            o_xyz="${axis_length/2} 0 0"
            o_rpy="0 ${pi/2} 0"
        />
    </link>

    <joint name="yaw_joint" type="revolute">
        <parent link="rudder_base" />
        <child link="rod_intermediate_link" />
        <origin xyz="${rudder_base_radius} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-${yaw_limit_rad}" upper="${yaw_limit_rad}" effort="100" velocity="100" />
    </joint>

    <link name="rod_intermediate_link">
        <inertial>
            <mass value="0.0001" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </inertial>
    </link>

    <joint name="pitch_joint" type="revolute">
        <parent link="rod_intermediate_link" />
        <child link="rod_link" />
        <axis xyz="0 1 0" />
        <limit lower="-${pitch_limit_rad}" upper="${pitch_limit_rad}" effort="100" velocity="100" />
    </joint>

    <link name="thruster_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${thruster_thickness} ${thruster_radius*2} ${thruster_blade_width}" />
            </geometry>
            <material name="blueish">
                <color rgba="0.3 0.3 0.9 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.005" />
            </geometry>
        </collision>
        <xacro:sphere_inertia m="0.001" r="0.005"
            o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="cylinder_thruster_joint" type="continuous">
        <parent link="rod_link" />
        <child link="thruster_link" />
        <origin xyz="${axis_length + thruster_thickness/2} 0 0" rpy="0 0 0" />
        <axis xyz="-1 0 0" />
    </joint>

</robot>